# Generated by Django 2.0.1 on 2020-03-04 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('roomtype', models.CharField(max_length=255)),
                ('capacity', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('check_in', models.DateTimeField(auto_now=True)),
                ('check_out', models.DateTimeField(auto_now=True)),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
                ('vat', models.IntegerField(blank=True, default=0, null=True)),
                ('service_charge', models.IntegerField(blank=True, default=0, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Hotels')),
            ],
        ),
        migrations.AddField(
            model_name='hotels',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Places'),
        ),
    ]
