# Generated by Django 2.0.1 on 2020-03-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_booked',
            field=models.IntegerField(default=0),
        ),
    ]
